### ISSUE TITLE
Access to more of bh_sne parameter

### ISSUE THREAD

**Issue by shaman-narayanasamy** [claczny/VizBin#27]
It would be nice if the user were to be able to access other bh_sne parameters such as "perplexity", etc.

-Shaman-

**Comment by claczny** [comment]
Are you referring to a command-line execution or execution via GUI?

For the latter, clicking on "Show additional options" will show different dialogues, including one to set the perplexity. Please note that this is something which can heavily affect the result. In fact, it can even result in pretty much uninterpretable (say "meaningless") 2D embeddings and should thus be used carefully and only if the default values do not result in a "reasonable" plot.
As described in the original BH-SNE paper, for sufficiently large datasets, the default values have been found to be generally very robust choices.

If you are referring to the command-line version, indeed, for completeness, these will be modifiable in a future version.

Thank you very much.

Best,

Cedric

**Comment by Dringite** [comment]
Is there any way to change parameters from python? Such as the number of iterations.

**Comment by claczny** [comment]
Hi @Dringite,

I am not sure what you mean by "python" here since VizBin is a Java-based application and the underlying code to BH-SNE is C-based.
However, more generally, it is possible to change the number of iterations but that would require to change it in the source code and recompile the BH-SNE binary.

Could you maybe share some info as to why you want to change the number of iterations? Do you want to increase or decrease that number?

Best,

Cedric

**Comment by claczny** [comment]
Closing as there was no follow-up.
